server:
  port: 8086
spring:
  mvc:

  datasource:
    platform: mysql
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://148.70.67.204:3306/monitor?characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: '123456'
    maxActive: 11
    maxIdle: 6
    minIdle: 3
    initialSize: 30
    testWhileIdle: true
    removeAbandoned: true
    logAbandoned: true
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .jsp
#  thymeleaf:
#    prefix: classpath:/templates/
#配置分页插件pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: trues
    params: count=countSql

#坑点0 配置mybatis的xml位置
mybatis:
  mapper-locations: classpath:mapper/*.xml
