package com.ideal.entity;

import java.util.Date;

public class OfferAttrEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_attr.OFFER_ATTR_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer offerAttrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_attr.OFFER_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer offerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_attr.PAR_OFFER_ATTR_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer parOfferAttrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_attr.ATTR_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer attrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_attr.DEFAULT_VALUE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String defaultValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_attr.OBJ_TYPE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String objType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_attr.OBJ_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer objId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_attr.MIN_VALUE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String minValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_attr.MAX_VALUE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String maxValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_attr.APPLY_REGION_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer applyRegionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_attr.STATUS_CD
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String statusCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_attr.CREATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer createStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_attr.UPDATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer updateStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_attr.CREATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_attr.STATUS_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date statusDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_attr.UPDATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_attr.OFFER_ATTR_ID
     *
     * @return the value of offer_attr.OFFER_ATTR_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getOfferAttrId() {
        return offerAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_attr.OFFER_ATTR_ID
     *
     * @param offerAttrId the value for offer_attr.OFFER_ATTR_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setOfferAttrId(Integer offerAttrId) {
        this.offerAttrId = offerAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_attr.OFFER_ID
     *
     * @return the value of offer_attr.OFFER_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getOfferId() {
        return offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_attr.OFFER_ID
     *
     * @param offerId the value for offer_attr.OFFER_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setOfferId(Integer offerId) {
        this.offerId = offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_attr.PAR_OFFER_ATTR_ID
     *
     * @return the value of offer_attr.PAR_OFFER_ATTR_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getParOfferAttrId() {
        return parOfferAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_attr.PAR_OFFER_ATTR_ID
     *
     * @param parOfferAttrId the value for offer_attr.PAR_OFFER_ATTR_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setParOfferAttrId(Integer parOfferAttrId) {
        this.parOfferAttrId = parOfferAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_attr.ATTR_ID
     *
     * @return the value of offer_attr.ATTR_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getAttrId() {
        return attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_attr.ATTR_ID
     *
     * @param attrId the value for offer_attr.ATTR_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setAttrId(Integer attrId) {
        this.attrId = attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_attr.DEFAULT_VALUE
     *
     * @return the value of offer_attr.DEFAULT_VALUE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_attr.DEFAULT_VALUE
     *
     * @param defaultValue the value for offer_attr.DEFAULT_VALUE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue == null ? null : defaultValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_attr.OBJ_TYPE
     *
     * @return the value of offer_attr.OBJ_TYPE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getObjType() {
        return objType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_attr.OBJ_TYPE
     *
     * @param objType the value for offer_attr.OBJ_TYPE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setObjType(String objType) {
        this.objType = objType == null ? null : objType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_attr.OBJ_ID
     *
     * @return the value of offer_attr.OBJ_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getObjId() {
        return objId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_attr.OBJ_ID
     *
     * @param objId the value for offer_attr.OBJ_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setObjId(Integer objId) {
        this.objId = objId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_attr.MIN_VALUE
     *
     * @return the value of offer_attr.MIN_VALUE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getMinValue() {
        return minValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_attr.MIN_VALUE
     *
     * @param minValue the value for offer_attr.MIN_VALUE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setMinValue(String minValue) {
        this.minValue = minValue == null ? null : minValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_attr.MAX_VALUE
     *
     * @return the value of offer_attr.MAX_VALUE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getMaxValue() {
        return maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_attr.MAX_VALUE
     *
     * @param maxValue the value for offer_attr.MAX_VALUE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setMaxValue(String maxValue) {
        this.maxValue = maxValue == null ? null : maxValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_attr.APPLY_REGION_ID
     *
     * @return the value of offer_attr.APPLY_REGION_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getApplyRegionId() {
        return applyRegionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_attr.APPLY_REGION_ID
     *
     * @param applyRegionId the value for offer_attr.APPLY_REGION_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setApplyRegionId(Integer applyRegionId) {
        this.applyRegionId = applyRegionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_attr.STATUS_CD
     *
     * @return the value of offer_attr.STATUS_CD
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getStatusCd() {
        return statusCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_attr.STATUS_CD
     *
     * @param statusCd the value for offer_attr.STATUS_CD
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd == null ? null : statusCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_attr.CREATE_STAFF
     *
     * @return the value of offer_attr.CREATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getCreateStaff() {
        return createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_attr.CREATE_STAFF
     *
     * @param createStaff the value for offer_attr.CREATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setCreateStaff(Integer createStaff) {
        this.createStaff = createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_attr.UPDATE_STAFF
     *
     * @return the value of offer_attr.UPDATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getUpdateStaff() {
        return updateStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_attr.UPDATE_STAFF
     *
     * @param updateStaff the value for offer_attr.UPDATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setUpdateStaff(Integer updateStaff) {
        this.updateStaff = updateStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_attr.CREATE_DATE
     *
     * @return the value of offer_attr.CREATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_attr.CREATE_DATE
     *
     * @param createDate the value for offer_attr.CREATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_attr.STATUS_DATE
     *
     * @return the value of offer_attr.STATUS_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getStatusDate() {
        return statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_attr.STATUS_DATE
     *
     * @param statusDate the value for offer_attr.STATUS_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_attr.UPDATE_DATE
     *
     * @return the value of offer_attr.UPDATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_attr.UPDATE_DATE
     *
     * @param updateDate the value for offer_attr.UPDATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}