package com.ideal.entity;

import java.util.Date;

public class OfferRelEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_rel.OFFER_REL_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer offerRelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_rel.OFFER_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer offerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_rel.PAR_OFFER_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer parOfferId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_rel.ROLE_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_rel.REL_TYPE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String relType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_rel.EFF_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date effDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_rel.EXP_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date expDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_rel.APPLY_REGION_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer applyRegionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_rel.STATUS_CD
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String statusCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_rel.CREATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer createStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_rel.UPDATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer updateStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_rel.CREATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_rel.STATUS_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date statusDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_rel.UPDATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_rel.REMARK
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_rel.OFFER_REL_ID
     *
     * @return the value of offer_rel.OFFER_REL_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getOfferRelId() {
        return offerRelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_rel.OFFER_REL_ID
     *
     * @param offerRelId the value for offer_rel.OFFER_REL_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setOfferRelId(Integer offerRelId) {
        this.offerRelId = offerRelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_rel.OFFER_ID
     *
     * @return the value of offer_rel.OFFER_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getOfferId() {
        return offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_rel.OFFER_ID
     *
     * @param offerId the value for offer_rel.OFFER_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setOfferId(Integer offerId) {
        this.offerId = offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_rel.PAR_OFFER_ID
     *
     * @return the value of offer_rel.PAR_OFFER_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getParOfferId() {
        return parOfferId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_rel.PAR_OFFER_ID
     *
     * @param parOfferId the value for offer_rel.PAR_OFFER_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setParOfferId(Integer parOfferId) {
        this.parOfferId = parOfferId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_rel.ROLE_ID
     *
     * @return the value of offer_rel.ROLE_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_rel.ROLE_ID
     *
     * @param roleId the value for offer_rel.ROLE_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_rel.REL_TYPE
     *
     * @return the value of offer_rel.REL_TYPE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getRelType() {
        return relType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_rel.REL_TYPE
     *
     * @param relType the value for offer_rel.REL_TYPE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setRelType(String relType) {
        this.relType = relType == null ? null : relType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_rel.EFF_DATE
     *
     * @return the value of offer_rel.EFF_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getEffDate() {
        return effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_rel.EFF_DATE
     *
     * @param effDate the value for offer_rel.EFF_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setEffDate(Date effDate) {
        this.effDate = effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_rel.EXP_DATE
     *
     * @return the value of offer_rel.EXP_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getExpDate() {
        return expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_rel.EXP_DATE
     *
     * @param expDate the value for offer_rel.EXP_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_rel.APPLY_REGION_ID
     *
     * @return the value of offer_rel.APPLY_REGION_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getApplyRegionId() {
        return applyRegionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_rel.APPLY_REGION_ID
     *
     * @param applyRegionId the value for offer_rel.APPLY_REGION_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setApplyRegionId(Integer applyRegionId) {
        this.applyRegionId = applyRegionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_rel.STATUS_CD
     *
     * @return the value of offer_rel.STATUS_CD
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getStatusCd() {
        return statusCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_rel.STATUS_CD
     *
     * @param statusCd the value for offer_rel.STATUS_CD
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd == null ? null : statusCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_rel.CREATE_STAFF
     *
     * @return the value of offer_rel.CREATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getCreateStaff() {
        return createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_rel.CREATE_STAFF
     *
     * @param createStaff the value for offer_rel.CREATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setCreateStaff(Integer createStaff) {
        this.createStaff = createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_rel.UPDATE_STAFF
     *
     * @return the value of offer_rel.UPDATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getUpdateStaff() {
        return updateStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_rel.UPDATE_STAFF
     *
     * @param updateStaff the value for offer_rel.UPDATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setUpdateStaff(Integer updateStaff) {
        this.updateStaff = updateStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_rel.CREATE_DATE
     *
     * @return the value of offer_rel.CREATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_rel.CREATE_DATE
     *
     * @param createDate the value for offer_rel.CREATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_rel.STATUS_DATE
     *
     * @return the value of offer_rel.STATUS_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getStatusDate() {
        return statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_rel.STATUS_DATE
     *
     * @param statusDate the value for offer_rel.STATUS_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_rel.UPDATE_DATE
     *
     * @return the value of offer_rel.UPDATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_rel.UPDATE_DATE
     *
     * @param updateDate the value for offer_rel.UPDATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_rel.REMARK
     *
     * @return the value of offer_rel.REMARK
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_rel.REMARK
     *
     * @param remark the value for offer_rel.REMARK
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}