package com.ideal.entity;

import java.util.Date;

public class OfferInstEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_inst.OFFER_INST_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer offerInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_inst.CUST_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer custId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_inst.OFFER_INST_TYPE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String offerInstType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_inst.OFFER_INST_NAME
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String offerInstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_inst.CUST_ORDER_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer custOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_inst.CUST_ORDER_NBR
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String custOrderNbr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_inst.EFF_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date effDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_inst.EXP_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date expDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_inst.REMARK
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_inst.STATUS_CD
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String statusCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_inst.CREATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer createStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_inst.UPDATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer updateStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_inst.CREATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_inst.STATUS_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date statusDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_inst.UPDATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_inst.OFFER_INST_ID
     *
     * @return the value of offer_inst.OFFER_INST_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getOfferInstId() {
        return offerInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_inst.OFFER_INST_ID
     *
     * @param offerInstId the value for offer_inst.OFFER_INST_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setOfferInstId(Integer offerInstId) {
        this.offerInstId = offerInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_inst.CUST_ID
     *
     * @return the value of offer_inst.CUST_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_inst.CUST_ID
     *
     * @param custId the value for offer_inst.CUST_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setCustId(Integer custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_inst.OFFER_INST_TYPE
     *
     * @return the value of offer_inst.OFFER_INST_TYPE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getOfferInstType() {
        return offerInstType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_inst.OFFER_INST_TYPE
     *
     * @param offerInstType the value for offer_inst.OFFER_INST_TYPE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setOfferInstType(String offerInstType) {
        this.offerInstType = offerInstType == null ? null : offerInstType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_inst.OFFER_INST_NAME
     *
     * @return the value of offer_inst.OFFER_INST_NAME
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getOfferInstName() {
        return offerInstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_inst.OFFER_INST_NAME
     *
     * @param offerInstName the value for offer_inst.OFFER_INST_NAME
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setOfferInstName(String offerInstName) {
        this.offerInstName = offerInstName == null ? null : offerInstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_inst.CUST_ORDER_ID
     *
     * @return the value of offer_inst.CUST_ORDER_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getCustOrderId() {
        return custOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_inst.CUST_ORDER_ID
     *
     * @param custOrderId the value for offer_inst.CUST_ORDER_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setCustOrderId(Integer custOrderId) {
        this.custOrderId = custOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_inst.CUST_ORDER_NBR
     *
     * @return the value of offer_inst.CUST_ORDER_NBR
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getCustOrderNbr() {
        return custOrderNbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_inst.CUST_ORDER_NBR
     *
     * @param custOrderNbr the value for offer_inst.CUST_ORDER_NBR
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setCustOrderNbr(String custOrderNbr) {
        this.custOrderNbr = custOrderNbr == null ? null : custOrderNbr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_inst.EFF_DATE
     *
     * @return the value of offer_inst.EFF_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getEffDate() {
        return effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_inst.EFF_DATE
     *
     * @param effDate the value for offer_inst.EFF_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setEffDate(Date effDate) {
        this.effDate = effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_inst.EXP_DATE
     *
     * @return the value of offer_inst.EXP_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getExpDate() {
        return expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_inst.EXP_DATE
     *
     * @param expDate the value for offer_inst.EXP_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_inst.REMARK
     *
     * @return the value of offer_inst.REMARK
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_inst.REMARK
     *
     * @param remark the value for offer_inst.REMARK
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_inst.STATUS_CD
     *
     * @return the value of offer_inst.STATUS_CD
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getStatusCd() {
        return statusCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_inst.STATUS_CD
     *
     * @param statusCd the value for offer_inst.STATUS_CD
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd == null ? null : statusCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_inst.CREATE_STAFF
     *
     * @return the value of offer_inst.CREATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getCreateStaff() {
        return createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_inst.CREATE_STAFF
     *
     * @param createStaff the value for offer_inst.CREATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setCreateStaff(Integer createStaff) {
        this.createStaff = createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_inst.UPDATE_STAFF
     *
     * @return the value of offer_inst.UPDATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getUpdateStaff() {
        return updateStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_inst.UPDATE_STAFF
     *
     * @param updateStaff the value for offer_inst.UPDATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setUpdateStaff(Integer updateStaff) {
        this.updateStaff = updateStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_inst.CREATE_DATE
     *
     * @return the value of offer_inst.CREATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_inst.CREATE_DATE
     *
     * @param createDate the value for offer_inst.CREATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_inst.STATUS_DATE
     *
     * @return the value of offer_inst.STATUS_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getStatusDate() {
        return statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_inst.STATUS_DATE
     *
     * @param statusDate the value for offer_inst.STATUS_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_inst.UPDATE_DATE
     *
     * @return the value of offer_inst.UPDATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_inst.UPDATE_DATE
     *
     * @param updateDate the value for offer_inst.UPDATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}