package com.ideal.entity;

import java.util.Date;

public class OfferEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer.OFFER_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer offerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer.COMMODITY_TYPE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer commodityType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer.OFFER_TYPE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String offerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer.OFFER_NAME
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String offerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer.OFFER_NBR
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String offerNbr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer.OFFER_DESC
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String offerDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer.EFF_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date effDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer.EXP_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date expDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer.PRICING
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Double pricing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer.REMARK
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer.MANAGE_REGION_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer manageRegionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer.STATUS_CD
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String statusCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer.CREATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer createStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer.UPDATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer updateStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer.CREATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer.STATUS_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date statusDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer.UPDATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer.OFFER_ID
     *
     * @return the value of offer.OFFER_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getOfferId() {
        return offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer.OFFER_ID
     *
     * @param offerId the value for offer.OFFER_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setOfferId(Integer offerId) {
        this.offerId = offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer.COMMODITY_TYPE
     *
     * @return the value of offer.COMMODITY_TYPE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getCommodityType() {
        return commodityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer.COMMODITY_TYPE
     *
     * @param commodityType the value for offer.COMMODITY_TYPE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setCommodityType(Integer commodityType) {
        this.commodityType = commodityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer.OFFER_TYPE
     *
     * @return the value of offer.OFFER_TYPE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getOfferType() {
        return offerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer.OFFER_TYPE
     *
     * @param offerType the value for offer.OFFER_TYPE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setOfferType(String offerType) {
        this.offerType = offerType == null ? null : offerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer.OFFER_NAME
     *
     * @return the value of offer.OFFER_NAME
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getOfferName() {
        return offerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer.OFFER_NAME
     *
     * @param offerName the value for offer.OFFER_NAME
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setOfferName(String offerName) {
        this.offerName = offerName == null ? null : offerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer.OFFER_NBR
     *
     * @return the value of offer.OFFER_NBR
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getOfferNbr() {
        return offerNbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer.OFFER_NBR
     *
     * @param offerNbr the value for offer.OFFER_NBR
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setOfferNbr(String offerNbr) {
        this.offerNbr = offerNbr == null ? null : offerNbr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer.OFFER_DESC
     *
     * @return the value of offer.OFFER_DESC
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getOfferDesc() {
        return offerDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer.OFFER_DESC
     *
     * @param offerDesc the value for offer.OFFER_DESC
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setOfferDesc(String offerDesc) {
        this.offerDesc = offerDesc == null ? null : offerDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer.EFF_DATE
     *
     * @return the value of offer.EFF_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getEffDate() {
        return effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer.EFF_DATE
     *
     * @param effDate the value for offer.EFF_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setEffDate(Date effDate) {
        this.effDate = effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer.EXP_DATE
     *
     * @return the value of offer.EXP_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getExpDate() {
        return expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer.EXP_DATE
     *
     * @param expDate the value for offer.EXP_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer.PRICING
     *
     * @return the value of offer.PRICING
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Double getPricing() {
        return pricing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer.PRICING
     *
     * @param pricing the value for offer.PRICING
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setPricing(Double pricing) {
        this.pricing = pricing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer.REMARK
     *
     * @return the value of offer.REMARK
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer.REMARK
     *
     * @param remark the value for offer.REMARK
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer.MANAGE_REGION_ID
     *
     * @return the value of offer.MANAGE_REGION_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getManageRegionId() {
        return manageRegionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer.MANAGE_REGION_ID
     *
     * @param manageRegionId the value for offer.MANAGE_REGION_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setManageRegionId(Integer manageRegionId) {
        this.manageRegionId = manageRegionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer.STATUS_CD
     *
     * @return the value of offer.STATUS_CD
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getStatusCd() {
        return statusCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer.STATUS_CD
     *
     * @param statusCd the value for offer.STATUS_CD
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd == null ? null : statusCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer.CREATE_STAFF
     *
     * @return the value of offer.CREATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getCreateStaff() {
        return createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer.CREATE_STAFF
     *
     * @param createStaff the value for offer.CREATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setCreateStaff(Integer createStaff) {
        this.createStaff = createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer.UPDATE_STAFF
     *
     * @return the value of offer.UPDATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getUpdateStaff() {
        return updateStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer.UPDATE_STAFF
     *
     * @param updateStaff the value for offer.UPDATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setUpdateStaff(Integer updateStaff) {
        this.updateStaff = updateStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer.CREATE_DATE
     *
     * @return the value of offer.CREATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer.CREATE_DATE
     *
     * @param createDate the value for offer.CREATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer.STATUS_DATE
     *
     * @return the value of offer.STATUS_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getStatusDate() {
        return statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer.STATUS_DATE
     *
     * @param statusDate the value for offer.STATUS_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer.UPDATE_DATE
     *
     * @return the value of offer.UPDATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer.UPDATE_DATE
     *
     * @param updateDate the value for offer.UPDATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}