package com.ideal.entity;

import java.util.Date;

public class ProdInstAttrEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_inst_attr.PROD_INST_ATTR_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer prodInstAttrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_inst_attr.CUST_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer custId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_inst_attr.ATTR_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer attrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_inst_attr.ATTR_VAL
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String attrVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_inst_attr.CUST_ORDER_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer custOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_inst_attr.CUST_ORDER_NBR
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String custOrderNbr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_inst_attr.EFF_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date effDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_inst_attr.EXP_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date expDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_inst_attr.REMARK
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_inst_attr.STATUS_CD
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String statusCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_inst_attr.CREATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer createStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_inst_attr.UPDATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer updateStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_inst_attr.CREATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_inst_attr.STATUS_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date statusDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_inst_attr.UPDATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_inst_attr.PROD_INST_ATTR_ID
     *
     * @return the value of prod_inst_attr.PROD_INST_ATTR_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getProdInstAttrId() {
        return prodInstAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_inst_attr.PROD_INST_ATTR_ID
     *
     * @param prodInstAttrId the value for prod_inst_attr.PROD_INST_ATTR_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setProdInstAttrId(Integer prodInstAttrId) {
        this.prodInstAttrId = prodInstAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_inst_attr.CUST_ID
     *
     * @return the value of prod_inst_attr.CUST_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_inst_attr.CUST_ID
     *
     * @param custId the value for prod_inst_attr.CUST_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setCustId(Integer custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_inst_attr.ATTR_ID
     *
     * @return the value of prod_inst_attr.ATTR_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getAttrId() {
        return attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_inst_attr.ATTR_ID
     *
     * @param attrId the value for prod_inst_attr.ATTR_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setAttrId(Integer attrId) {
        this.attrId = attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_inst_attr.ATTR_VAL
     *
     * @return the value of prod_inst_attr.ATTR_VAL
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getAttrVal() {
        return attrVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_inst_attr.ATTR_VAL
     *
     * @param attrVal the value for prod_inst_attr.ATTR_VAL
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setAttrVal(String attrVal) {
        this.attrVal = attrVal == null ? null : attrVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_inst_attr.CUST_ORDER_ID
     *
     * @return the value of prod_inst_attr.CUST_ORDER_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getCustOrderId() {
        return custOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_inst_attr.CUST_ORDER_ID
     *
     * @param custOrderId the value for prod_inst_attr.CUST_ORDER_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setCustOrderId(Integer custOrderId) {
        this.custOrderId = custOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_inst_attr.CUST_ORDER_NBR
     *
     * @return the value of prod_inst_attr.CUST_ORDER_NBR
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getCustOrderNbr() {
        return custOrderNbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_inst_attr.CUST_ORDER_NBR
     *
     * @param custOrderNbr the value for prod_inst_attr.CUST_ORDER_NBR
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setCustOrderNbr(String custOrderNbr) {
        this.custOrderNbr = custOrderNbr == null ? null : custOrderNbr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_inst_attr.EFF_DATE
     *
     * @return the value of prod_inst_attr.EFF_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getEffDate() {
        return effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_inst_attr.EFF_DATE
     *
     * @param effDate the value for prod_inst_attr.EFF_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setEffDate(Date effDate) {
        this.effDate = effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_inst_attr.EXP_DATE
     *
     * @return the value of prod_inst_attr.EXP_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getExpDate() {
        return expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_inst_attr.EXP_DATE
     *
     * @param expDate the value for prod_inst_attr.EXP_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_inst_attr.REMARK
     *
     * @return the value of prod_inst_attr.REMARK
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_inst_attr.REMARK
     *
     * @param remark the value for prod_inst_attr.REMARK
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_inst_attr.STATUS_CD
     *
     * @return the value of prod_inst_attr.STATUS_CD
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getStatusCd() {
        return statusCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_inst_attr.STATUS_CD
     *
     * @param statusCd the value for prod_inst_attr.STATUS_CD
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd == null ? null : statusCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_inst_attr.CREATE_STAFF
     *
     * @return the value of prod_inst_attr.CREATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getCreateStaff() {
        return createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_inst_attr.CREATE_STAFF
     *
     * @param createStaff the value for prod_inst_attr.CREATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setCreateStaff(Integer createStaff) {
        this.createStaff = createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_inst_attr.UPDATE_STAFF
     *
     * @return the value of prod_inst_attr.UPDATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getUpdateStaff() {
        return updateStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_inst_attr.UPDATE_STAFF
     *
     * @param updateStaff the value for prod_inst_attr.UPDATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setUpdateStaff(Integer updateStaff) {
        this.updateStaff = updateStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_inst_attr.CREATE_DATE
     *
     * @return the value of prod_inst_attr.CREATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_inst_attr.CREATE_DATE
     *
     * @param createDate the value for prod_inst_attr.CREATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_inst_attr.STATUS_DATE
     *
     * @return the value of prod_inst_attr.STATUS_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getStatusDate() {
        return statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_inst_attr.STATUS_DATE
     *
     * @param statusDate the value for prod_inst_attr.STATUS_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_inst_attr.UPDATE_DATE
     *
     * @return the value of prod_inst_attr.UPDATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_inst_attr.UPDATE_DATE
     *
     * @param updateDate the value for prod_inst_attr.UPDATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}