package com.ideal.entity;

import java.util.Date;

public class ProductEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PROD_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer prodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PROD_NBR
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String prodNbr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PROD_NAME
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String prodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PROD_DESC
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String prodDesc;
    
    
    private String factoryPricing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.EFF_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date effDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.EXP_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date expDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PROD_TYPE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String prodType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.BASE_OFFER_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer baseOfferId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.STATUS_CD
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String statusCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.CREATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer createStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.UPDATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer updateStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.CREATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.STATUS_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date statusDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.UPDATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.REMARK
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PROD_ID
     *
     * @return the value of product.PROD_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PROD_ID
     *
     * @param prodId the value for product.PROD_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setProdId(Integer prodId) {
        this.prodId = prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PROD_NBR
     *
     * @return the value of product.PROD_NBR
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getProdNbr() {
        return prodNbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PROD_NBR
     *
     * @param prodNbr the value for product.PROD_NBR
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setProdNbr(String prodNbr) {
        this.prodNbr = prodNbr == null ? null : prodNbr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PROD_NAME
     *
     * @return the value of product.PROD_NAME
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getProdName() {
        return prodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PROD_NAME
     *
     * @param prodName the value for product.PROD_NAME
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setProdName(String prodName) {
        this.prodName = prodName == null ? null : prodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PROD_DESC
     *
     * @return the value of product.PROD_DESC
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getProdDesc() {
        return prodDesc;
    }
    

    public String getFactoryPricing() {
		return factoryPricing;
	}

	public void setFactoryPricing(String factoryPricing) {
		this.factoryPricing = factoryPricing == null ? null : factoryPricing.trim();
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PROD_DESC
     *
     * @param prodDesc the value for product.PROD_DESC
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setProdDesc(String prodDesc) {
        this.prodDesc = prodDesc == null ? null : prodDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.EFF_DATE
     *
     * @return the value of product.EFF_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getEffDate() {
        return effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.EFF_DATE
     *
     * @param effDate the value for product.EFF_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setEffDate(Date effDate) {
        this.effDate = effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.EXP_DATE
     *
     * @return the value of product.EXP_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getExpDate() {
        return expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.EXP_DATE
     *
     * @param expDate the value for product.EXP_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PROD_TYPE
     *
     * @return the value of product.PROD_TYPE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getProdType() {
        return prodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PROD_TYPE
     *
     * @param prodType the value for product.PROD_TYPE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setProdType(String prodType) {
        this.prodType = prodType == null ? null : prodType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.BASE_OFFER_ID
     *
     * @return the value of product.BASE_OFFER_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getBaseOfferId() {
        return baseOfferId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.BASE_OFFER_ID
     *
     * @param baseOfferId the value for product.BASE_OFFER_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setBaseOfferId(Integer baseOfferId) {
        this.baseOfferId = baseOfferId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.STATUS_CD
     *
     * @return the value of product.STATUS_CD
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getStatusCd() {
        return statusCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.STATUS_CD
     *
     * @param statusCd the value for product.STATUS_CD
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd == null ? null : statusCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.CREATE_STAFF
     *
     * @return the value of product.CREATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getCreateStaff() {
        return createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.CREATE_STAFF
     *
     * @param createStaff the value for product.CREATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setCreateStaff(Integer createStaff) {
        this.createStaff = createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.UPDATE_STAFF
     *
     * @return the value of product.UPDATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getUpdateStaff() {
        return updateStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.UPDATE_STAFF
     *
     * @param updateStaff the value for product.UPDATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setUpdateStaff(Integer updateStaff) {
        this.updateStaff = updateStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.CREATE_DATE
     *
     * @return the value of product.CREATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.CREATE_DATE
     *
     * @param createDate the value for product.CREATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.STATUS_DATE
     *
     * @return the value of product.STATUS_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getStatusDate() {
        return statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.STATUS_DATE
     *
     * @param statusDate the value for product.STATUS_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.UPDATE_DATE
     *
     * @return the value of product.UPDATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.UPDATE_DATE
     *
     * @param updateDate the value for product.UPDATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.REMARK
     *
     * @return the value of product.REMARK
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.REMARK
     *
     * @param remark the value for product.REMARK
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}