package com.ideal.entity;

import java.util.Date;

public class ProdAttrEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_attr.PROD_ATTR_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer prodAttrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_attr.PROD_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer prodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_attr.ATTR_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer attrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_attr.PAR_PROD_ATTR_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer parProdAttrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_attr.DEFAULT_VALUE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String defaultValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_attr.COMMENTS
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String comments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_attr.IF_NECESSARY
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String ifNecessary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_attr.IF_TO_CHANGE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String ifToChange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_attr.APPLY_REGION_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer applyRegionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_attr.EFF_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date effDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_attr.EXP_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date expDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_attr.STATUS_CD
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String statusCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_attr.CREATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer createStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_attr.UPDATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer updateStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_attr.CREATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_attr.STATUS_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date statusDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_attr.UPDATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_attr.REMARK
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_attr.PROD_ATTR_ID
     *
     * @return the value of prod_attr.PROD_ATTR_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getProdAttrId() {
        return prodAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_attr.PROD_ATTR_ID
     *
     * @param prodAttrId the value for prod_attr.PROD_ATTR_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setProdAttrId(Integer prodAttrId) {
        this.prodAttrId = prodAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_attr.PROD_ID
     *
     * @return the value of prod_attr.PROD_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_attr.PROD_ID
     *
     * @param prodId the value for prod_attr.PROD_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setProdId(Integer prodId) {
        this.prodId = prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_attr.ATTR_ID
     *
     * @return the value of prod_attr.ATTR_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getAttrId() {
        return attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_attr.ATTR_ID
     *
     * @param attrId the value for prod_attr.ATTR_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setAttrId(Integer attrId) {
        this.attrId = attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_attr.PAR_PROD_ATTR_ID
     *
     * @return the value of prod_attr.PAR_PROD_ATTR_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getParProdAttrId() {
        return parProdAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_attr.PAR_PROD_ATTR_ID
     *
     * @param parProdAttrId the value for prod_attr.PAR_PROD_ATTR_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setParProdAttrId(Integer parProdAttrId) {
        this.parProdAttrId = parProdAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_attr.DEFAULT_VALUE
     *
     * @return the value of prod_attr.DEFAULT_VALUE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_attr.DEFAULT_VALUE
     *
     * @param defaultValue the value for prod_attr.DEFAULT_VALUE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue == null ? null : defaultValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_attr.COMMENTS
     *
     * @return the value of prod_attr.COMMENTS
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_attr.COMMENTS
     *
     * @param comments the value for prod_attr.COMMENTS
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_attr.IF_NECESSARY
     *
     * @return the value of prod_attr.IF_NECESSARY
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getIfNecessary() {
        return ifNecessary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_attr.IF_NECESSARY
     *
     * @param ifNecessary the value for prod_attr.IF_NECESSARY
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setIfNecessary(String ifNecessary) {
        this.ifNecessary = ifNecessary == null ? null : ifNecessary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_attr.IF_TO_CHANGE
     *
     * @return the value of prod_attr.IF_TO_CHANGE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getIfToChange() {
        return ifToChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_attr.IF_TO_CHANGE
     *
     * @param ifToChange the value for prod_attr.IF_TO_CHANGE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setIfToChange(String ifToChange) {
        this.ifToChange = ifToChange == null ? null : ifToChange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_attr.APPLY_REGION_ID
     *
     * @return the value of prod_attr.APPLY_REGION_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getApplyRegionId() {
        return applyRegionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_attr.APPLY_REGION_ID
     *
     * @param applyRegionId the value for prod_attr.APPLY_REGION_ID
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setApplyRegionId(Integer applyRegionId) {
        this.applyRegionId = applyRegionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_attr.EFF_DATE
     *
     * @return the value of prod_attr.EFF_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getEffDate() {
        return effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_attr.EFF_DATE
     *
     * @param effDate the value for prod_attr.EFF_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setEffDate(Date effDate) {
        this.effDate = effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_attr.EXP_DATE
     *
     * @return the value of prod_attr.EXP_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getExpDate() {
        return expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_attr.EXP_DATE
     *
     * @param expDate the value for prod_attr.EXP_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_attr.STATUS_CD
     *
     * @return the value of prod_attr.STATUS_CD
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getStatusCd() {
        return statusCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_attr.STATUS_CD
     *
     * @param statusCd the value for prod_attr.STATUS_CD
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd == null ? null : statusCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_attr.CREATE_STAFF
     *
     * @return the value of prod_attr.CREATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getCreateStaff() {
        return createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_attr.CREATE_STAFF
     *
     * @param createStaff the value for prod_attr.CREATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setCreateStaff(Integer createStaff) {
        this.createStaff = createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_attr.UPDATE_STAFF
     *
     * @return the value of prod_attr.UPDATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getUpdateStaff() {
        return updateStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_attr.UPDATE_STAFF
     *
     * @param updateStaff the value for prod_attr.UPDATE_STAFF
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setUpdateStaff(Integer updateStaff) {
        this.updateStaff = updateStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_attr.CREATE_DATE
     *
     * @return the value of prod_attr.CREATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_attr.CREATE_DATE
     *
     * @param createDate the value for prod_attr.CREATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_attr.STATUS_DATE
     *
     * @return the value of prod_attr.STATUS_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getStatusDate() {
        return statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_attr.STATUS_DATE
     *
     * @param statusDate the value for prod_attr.STATUS_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_attr.UPDATE_DATE
     *
     * @return the value of prod_attr.UPDATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_attr.UPDATE_DATE
     *
     * @param updateDate the value for prod_attr.UPDATE_DATE
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_attr.REMARK
     *
     * @return the value of prod_attr.REMARK
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_attr.REMARK
     *
     * @param remark the value for prod_attr.REMARK
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}